# Database
spring.datasource.url=jdbc:mysql://localhost:3306/moneymanager
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.servlet.context-path=/api/v1.0

#Email
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a3ee0c001@smtp-brevo.com
spring.mail.password=xsmtpsib-4e70b2b233d4931a33976b57ada25dbbeda9aa8d9dcff9bf3c7fa9c3730fbec6-drPYMKKpvbYpID7e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=sambhavg1710@gmail.com

#Jwt
jwt.secret.key=sambhav-money-manager-secure-jwt-secret-key-2026-very-strong